let netUser=null,issueMarkers=[],seenPending=new Set(),activeMetricsPanel=null,suggestedBorders=L.layerGroup().addTo(map),linkLayers=new Map();
const portalStyle=document.createElement('style');
portalStyle.textContent=`.auth-overlay{position:fixed;inset:0;z-index:5000;background:#07101e;display:grid;place-items:center}.auth-card{width:min(390px,92vw);background:#101d31;border:1px solid #304763;border-radius:14px;padding:24px;box-shadow:0 20px 70px #000a}.auth-card h2{margin-top:0}.account{font-size:12px;color:#afbed1}.pop-marker{width:118px;transform:translate(-59px,-28px);background:#0d1a2cf2;border:2px solid #38bdf8;border-radius:9px;color:#fff;padding:5px 8px;text-align:center;box-shadow:0 3px 10px #0008}.pop-marker b{display:block;color:#7dd3fc;font-size:10px;letter-spacing:.12em}.pop-marker span{display:block;font-size:11px;line-height:1.15;overflow-wrap:anywhere}.pop-marker small{display:block;color:#cbd5e1;font-size:10px;margin-top:2px}.issue-badge{width:24px;height:24px;border-radius:50%;display:grid;place-items:center;color:#111;font:800 17px/1 system-ui;border:2px solid #fff;box-shadow:0 2px 7px #000b}.issue-medium{background:#fde047}.issue-severe{background:#fb923c}.issue-disaster{background:#ff2020;color:#fff}.issue-x{border-radius:6px;position:relative}.issue-x:before,.issue-x:after{content:'';position:absolute;left:4px;top:9px;width:13px;height:3px;border-radius:3px;background:#fff}.issue-x:before{transform:rotate(45deg)}.issue-x:after{transform:rotate(-45deg)}.issue-list{display:grid;gap:8px}.issue-card{border:1px solid #38506f;border-radius:8px;padding:10px;background:#14243b}.suggested-route-label{display:inline-block;margin-top:6px;padding:3px 7px;border:1px solid #38bdf8;border-radius:10px;color:#7dd3fc;font-weight:700}.role-technician .leaflet-draw,.role-technician #newCto,.role-technician #newHost{display:none!important}.role-admin .leaflet-draw-edit-remove{display:none!important}`;
document.head.append(portalStyle);
document.querySelector('header').insertAdjacentHTML('beforeend','<span id="account" class="account"></span><button id="issuesButton" style="display:none">Erros <b id="issueCount">0</b></button><button id="auditButton" style="display:none">Log de ações</button><button id="usersButton" style="display:none">Usuários</button><button id="licenseButton" style="display:none">Licença</button><button id="logoutButton" style="display:none">Sair</button>');
document.body.insertAdjacentHTML('beforeend','<div id="authOverlay" class="auth-overlay"><div class="auth-card"><h2>LVL - NetAtlas</h2><p class="muted">Entre para acessar o mapa da rede.</p><form id="loginForm"><label>Usuário</label><input id="loginUser" autocomplete="username" required><label>Senha</label><input id="loginPassword" type="password" autocomplete="current-password" required><p id="loginError" class="form-error"></p><button class="primary" type="submit">Entrar</button></form></div></div>');

api=async function(url,opt={}){let r=await fetch(url,{headers:{'Content-Type':'application/json'},...opt});if(r.status===401){showLogin();throw Error('Sessão expirada')}if(!r.ok){let x=await r.json().catch(()=>({}));throw Error(typeof x.detail==='string'?x.detail:JSON.stringify(x.detail||r.statusText))}return r.status===204?null:r.json()};
function showLogin(){document.getElementById('authOverlay').style.display='grid';document.getElementById('loginPassword').value='';document.getElementById('loginUser').focus()}
document.getElementById('loginForm').onsubmit=async e=>{e.preventDefault();let error=document.getElementById('loginError');error.textContent='Entrando…';let r=await fetch('/api/auth/login',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({username:document.getElementById('loginUser').value,password:document.getElementById('loginPassword').value})});if(!r.ok){let x=await r.json().catch(()=>({}));error.textContent=x.detail||'Não foi possível entrar';return}location.reload()};
document.getElementById('logoutButton').onclick=async()=>{await fetch('/api/auth/logout',{method:'POST'});location.reload()};
function canOperate(){return netUser&&['superadmin','admin'].includes(netUser.role)}
function applyRole(){document.body.classList.add(`role-${netUser.role}`);document.getElementById('authOverlay').style.display='none';document.getElementById('account').textContent=`${netUser.display_name} · ${netUser.role}`;document.getElementById('logoutButton').style.display='inline-block';document.getElementById('issuesButton').style.display='inline-block';if(netUser.role==='superadmin'){document.getElementById('usersButton').style.display='inline-block';document.getElementById('auditButton').style.display='inline-block';document.getElementById('licenseButton').style.display='inline-block'}}

const originalRefreshMarkers=refreshMarkers;
map.off('zoomend',originalRefreshMarkers);
refreshMarkers=function(){let z=map.getZoom(),popView=z<=15;for(let m of markers.values()){let hide=m.net.kind==='device'?popView:m.net.kind==='cto'?z<16:m.net.kind==='cloud'?z<14:false;if(hide){if(map.hasLayer(m))map.removeLayer(m)}else{m.setIcon(mkIcon(m.net));if(!map.hasLayer(m))m.addTo(map)}}siteMarkers.forEach(m=>{if(popView){if(!map.hasLayer(m))m.addTo(map)}else if(map.hasLayer(m))map.removeLayer(m)});refreshIssueVisibility()};
map.on('zoomend',refreshMarkers);

loadTopology=async function(){let data=await api('/api/topology'),bounds=[],count=0;data.sites.forEach(s=>{bounds.push([s.latitude,s.longitude]);s.devices.forEach((d,i)=>{count++;d.kind='device';d.pop_id=s.id;d.pop_name=s.name;d.down=d.zabbix_hostid&&Number(d.availability)===2;d.planned=d.netbox_status==='planned';let p=d.latitude!=null?[d.latitude,d.longitude]:offset(s.latitude,s.longitude,i,s.devices.length);addMarker(d,p)});let label=s.name.replace(/^CENTRAL\s+/i,''),icon=L.divIcon({className:'',iconSize:[118,58],iconAnchor:[59,29],html:`<div class="pop-marker"><b>POP</b><span>${esc(label)}</span><small>${s.devices.length} host${s.devices.length===1?'':'s'}</small></div>`}),sm=L.marker([s.latitude,s.longitude],{icon,title:`POP ${label}`});sm.on('click',()=>map.setView([s.latitude,s.longitude],16));siteMarkers.push(sm)});if(bounds.length)map.fitBounds(bounds,{padding:[50,50]});document.getElementById('summary').textContent=`${data.sites.length} POPs · ${count} equipamentos`;await loadNodes();refreshMarkers()};

const originalStartMove=startMove,originalBeginLink=beginLink,originalChooseElementAt=chooseElementAt;
startMove=function(m){if(!canOperate()){hint('Seu perfil permite somente visualizar e reportar erros.');return}originalStartMove(m)};
beginLink=function(m,x){if(!canOperate()){hint('Seu perfil não permite criar enlaces.');return}originalBeginLink(m,x)};
chooseElementAt=function(p){if(!canOperate()){hint('Seu perfil não permite adicionar elementos.');return}originalChooseElementAt(p)};
const originalAddMarker=addMarker;
addMarker=function(d,point){let m=originalAddMarker(d,point);if(d.kind==='cto'||d.kind==='device'){m.off('contextmenu');m.on('contextmenu',e=>{L.DomEvent.stopPropagation(e);if(mode)return;let isHost=d.kind==='device',canDelete=canOperate(),label=isHost?'Host':'CTO',p=L.popup().setLatLng(e.latlng).setContent(`<div class="link-menu"><b>${esc(d.name)}</b><button id="moveElement">Mover</button>${canDelete?`<button id="deleteElementHere" class="danger">Excluir ${label}</button>`:''}</div>`).openOn(map);setTimeout(()=>{let move=document.getElementById('moveElement'),remove=document.getElementById('deleteElementHere');if(move)move.onclick=()=>{map.closePopup(p);startMove(m)};if(remove)remove.onclick=()=>{map.closePopup(p);isHost?deleteHostConfirmed(m):deleteCtoConfirmed(m)}},0)})}return m};

function reportButton(target){let old=document.getElementById('reportIssue');if(old)old.remove();let b=document.createElement('button');b.id='reportIssue';b.className='panel-action';b.textContent='Reportar erro';b.onclick=()=>openIssueForm(target);document.getElementById('panelBody').append(b)}
const originalOpenHostPanel=openHostPanel;
openHostPanel=async function(m){await originalOpenHostPanel(m);if(m.net.kind==='cto'&&canOperate()){let b=document.createElement('button');b.id='deleteCto';b.className='panel-action danger';b.textContent='Excluir CTO';b.onclick=()=>deleteCtoConfirmed(m);document.getElementById('panelBody').append(b)}if(m.net.kind==='host'&&canOperate()){let b=document.createElement('button');b.id='validateProvisionalHost';b.className='panel-action';b.textContent='Validar com host do Zabbix';b.onclick=()=>validateProvisionalHost(m);document.getElementById('panelBody').append(b)}if(m.net.kind==='device'&&canOperate()){let b=document.createElement('button');b.id='deleteHost';b.className='panel-action danger';b.textContent='Excluir Host';b.onclick=()=>deleteHostConfirmed(m);document.getElementById('panelBody').append(b)}reportButton({kind:m.net.kind==='device'?'device':'node',id:m.net.id,name:m.net.name});activeMetricsPanel=m.net.kind==='device'?{kind:'host',markerKey:`device:${m.net.id}`} :null};
const originalOpenLinkPanel=openLinkPanel;
openLinkPanel=async function(l,layer,clickedLatLng=null){await originalOpenLinkPanel(l,layer,clickedLatLng);if(netUser.role!=='superadmin'){let del=document.getElementById('deleteLink');if(del)del.remove()}if(!canOperate()){for(let id of ['editLink','renameLink','replaceSourceInterface','replaceTargetInterface','insertCtoInLink']){let button=document.getElementById(id);if(button)button.remove()}}reportButton({kind:'link',id:l.id,name:l.name});activeMetricsPanel={kind:'link',id:Number(l.id)}};
const originalClosePanel=closePanel;
closePanel=function(){activeMetricsPanel=null;originalClosePanel()};

function roadPointKey(p){return`${Number(p[0]).toFixed(5)},${Number(p[1]).toFixed(5)}`}
function roadSegmentKey(a,b){let x=roadPointKey(a),y=roadPointKey(b);return x<y?`${x}|${y}`:`${y}|${x}`}
function laneNumber(index,count){return index-(count-1)/2}
function linkWeight(){let z=map.getZoom();return z<=11?1.5:z===12?2:z===13?3:z===14?4:5}
function separatedCoordinates(link,segments){let cs=link.geometry.coordinates.map(p=>[Number(p[0]),Number(p[1])]);if(cs.length<2)return cs;let offsets=cs.map(()=>({x:0,y:0,n:0})),spacing=linkWeight()+2;for(let i=0;i<cs.length-1;i++){let group=segments.get(roadSegmentKey(cs[i],cs[i+1]))||[link],ordered=[...group].sort((a,b)=>Number(a.id)-Number(b.id)),lane=laneNumber(ordered.findIndex(x=>Number(x.id)===Number(link.id)),ordered.length);if(!lane)continue;let a=map.latLngToLayerPoint([cs[i][1],cs[i][0]]),b=map.latLngToLayerPoint([cs[i+1][1],cs[i+1][0]]),dx=b.x-a.x,dy=b.y-a.y,n=Math.hypot(dx,dy);if(!n)continue;let ox=-dy/n*lane*spacing,oy=dx/n*lane*spacing;for(let j of [i,i+1]){offsets[j].x+=ox;offsets[j].y+=oy;offsets[j].n++}}return cs.map((p,i)=>{let o=offsets[i];if(!o.n)return p;let base=map.latLngToLayerPoint([p[1],p[0]]),ll=map.layerPointToLatLng([base.x+o.x/o.n,base.y+o.y/o.n]);return[ll.lng,ll.lat]})}
function pointSegmentDistance(p,a,b){let dx=b.x-a.x,dy=b.y-a.y;if(!dx&&!dy)return p.distanceTo(a);let t=Math.max(0,Math.min(1,((p.x-a.x)*dx+(p.y-a.y)*dy)/(dx*dx+dy*dy))),x=a.x+t*dx,y=a.y+t*dy;return Math.hypot(p.x-x,p.y-y)}
function linksNear(latlng){let p=map.latLngToLayerPoint(latlng);return links.filter(l=>!(l.trunk_group&&!l.is_trunk)).filter(l=>{let cs=l.display_coordinates||l.geometry.coordinates;for(let i=1;i<cs.length;i++){let a=map.latLngToLayerPoint([cs[i-1][1],cs[i-1][0]]),b=map.latLngToLayerPoint([cs[i][1],cs[i][0]]);if(pointSegmentDistance(p,a,b)<=11)return true}return false}).sort((a,b)=>Number(a.id)-Number(b.id))}
function chooseLinkAt(latlng,fallback){let p=map.latLngToLayerPoint(latlng),display=fallback.display_coordinates||fallback.geometry.coordinates,best={distance:Infinity,index:1};for(let i=1;i<display.length;i++){let a=map.latLngToLayerPoint([display[i-1][1],display[i-1][0]]),b=map.latLngToLayerPoint([display[i][1],display[i][0]]),distance=pointSegmentDistance(p,a,b);if(distance<best.distance)best={distance,index:i}}let original=fallback.geometry.coordinates,key=roadSegmentKey(original[best.index-1],original[best.index]),nearby=links.filter(l=>!(l.trunk_group&&!l.is_trunk)).filter(l=>{let cs=l.geometry.coordinates;for(let i=1;i<cs.length;i++)if(roadSegmentKey(cs[i-1],cs[i])===key)return true;return false}).sort((a,b)=>Number(a.id)-Number(b.id));if(nearby.length<2){let layer=linkLayers.get(Number(fallback.id));if(layer)openLinkPanel(fallback,layer,latlng);return}let popup=L.popup({maxWidth:360}).setLatLng(latlng).setContent(`<div class="link-menu"><b>${nearby.length} enlaces neste trecho</b>${nearby.map(l=>`<button class="choose-overlap-link" data-id="${l.id}"><span class="${l.status==='up'?'updot':l.status==='down'?'downdot':'unkdot'}">●</span> ${esc(l.name)}${l.is_trunk?'<br><small>Eth-Trunk</small>':l.route_mode==='suggested'?'<br><small>Trajeto sugerido</small>':''}</button>`).join('')}</div>`).openOn(map);setTimeout(()=>document.querySelectorAll('.choose-overlap-link').forEach(b=>b.onclick=()=>{let l=links.find(x=>Number(x.id)===Number(b.dataset.id)),layer=linkLayers.get(Number(b.dataset.id));map.closePopup(popup);if(l&&layer)openLinkPanel(l,layer,latlng)}),0)}
function renderLinks(){editable.clearLayers();suggestedBorders.clearLayers();linkLayers.clear();let visibleLinks=links.filter(l=>!(l.trunk_group&&!l.is_trunk)),segments=new Map(),weight=linkWeight();visibleLinks.forEach(l=>{let cs=l.geometry.coordinates;for(let i=1;i<cs.length;i++){let key=roadSegmentKey(cs[i-1],cs[i]);if(!segments.has(key))segments.set(key,[]);segments.get(key).push(l)}});visibleLinks.filter(l=>l.is_trunk&&l.trunk_group).forEach(trunk=>{let latlngs=trunk.geometry.coordinates.map(p=>[p[1],p[0]]);L.polyline(latlngs,{color:'#111827',weight:weight+6,opacity:.78,interactive:false,className:'eth-trunk-sleeve'}).addTo(suggestedBorders)});visibleLinks.forEach(l=>{let display=separatedCoordinates(l,segments),latlngs=display.map(p=>[p[1],p[0]]);l.display_coordinates=display;if(l.route_mode==='suggested')L.polyline(latlngs,{color:'#0284c7',weight:weight+4,opacity:.95,interactive:false,className:'suggested-route-border'}).addTo(suggestedBorders);let state=l.status==='up'?'up':l.status==='down'?'down':'unknown',layer=L.polyline(latlngs,{color:lineColor(l.status),weight,className:`net-link net-link-${state} ${l.is_trunk?'eth-trunk-main':''}`,bubblingMouseEvents:false});layer.linkId=l.id;linkLayers.set(Number(l.id),layer);layer.on('click',e=>chooseLinkAt(e.latlng,l));layer.on('contextmenu',e=>{if(e.originalEvent)L.DomEvent.preventDefault(e.originalEvent);if(mode)return;let popup=L.popup({closeButton:true}).setLatLng(e.latlng).setContent(`<div class="link-menu"><b>${esc(l.name)}</b>${l.is_trunk?'<small>Eth-Trunk</small>':l.route_mode==='suggested'?'<small>Trajeto sugerido</small>':''}<button id="openLinkDetails">Abrir detalhes</button><button id="removeLinkHere" class="danger">Excluir enlace</button></div>`).openOn(map);setTimeout(()=>{let open=document.getElementById('openLinkDetails'),remove=document.getElementById('removeLinkHere');if(open)open.onclick=()=>{map.closePopup(popup);openLinkPanel(l,layer,e.latlng)};if(remove)remove.onclick=()=>{map.closePopup(popup);deleteLinkConfirmed(l)}},0)});editable.addLayer(layer)})}
loadLinks=async function(){links=await api('/api/links');renderLinks()};
map.on('zoomend',()=>{if(!mode&&!document.querySelector('.leaflet-editing-icon')&&links.length)renderLinks()});

function openIssueForm(target){modal('Reportar erro',`<form id="issueForm"><p><b>${esc(target.name)}</b></p><label>Classificação</label><select id="issueSeverity"><option value="medium">Médio — amarelo</option><option value="severe">Grave — laranja</option><option value="disaster">Desastre — vermelho</option></select><label>Descrição breve</label><textarea id="issueDescription" maxlength="1000" required style="width:100%;min-height:95px;background:#091526;color:#fff;border:1px solid #38506f;border-radius:6px;padding:9px"></textarea><p id="issueError" class="form-error"></p><button class="primary" type="submit">Reportar erro</button></form>`);document.getElementById('issueForm').onsubmit=async e=>{e.preventDefault();try{let result=await api('/api/issues',{method:'POST',body:JSON.stringify({target_kind:target.kind,target_id:target.id,target_name:target.name,severity:document.getElementById('issueSeverity').value,description:document.getElementById('issueDescription').value.trim()})});closeModal();await loadIssues(false);hint(result.status==='pending'?'Erro enviado para validação.':'Erro registrado e validado.')}catch(x){document.getElementById('issueError').textContent=x.message}}};
function issueRank(s){return s==='disaster'?3:s==='severe'?2:1}
function badgeFor(issue){let isX=issue.status!=='pending'&&issue.severity==='disaster',symbol=issue.status==='pending'?'?':isX?'':'!';return L.divIcon({className:'',iconSize:[24,24],iconAnchor:[12,12],html:`<div class="issue-badge issue-${issue.severity} ${isX?'issue-x':''}">${symbol}</div>`})}
function issueLabel(value){return({medium:'Médio',severe:'Grave',disaster:'Desastre',pending:'Pendente de validação',validated:'Validado',resolved:'Resolvido'})[value]||value}
function showIssueDetails(issue){modal('Detalhes do erro',`<div class="issue-card"><h3>${esc(issue.target_name)}</h3><p><b>Classificação:</b> ${esc(issueLabel(issue.severity))}<br><b>Status:</b> ${esc(issueLabel(issue.status))}<br><b>Reportado por:</b> ${esc(issue.reported_by_name)}${issue.validated_by_name?`<br><b>Validado por:</b> ${esc(issue.validated_by_name)}`:''}</p><p>${esc(issue.description)}</p><small>Registrado em ${new Date(issue.created_at).toLocaleString('pt-BR')}</small>${issue.status==='pending'&&canOperate()?`<button id="detailValidate" class="panel-action">Validar erro</button>`:''}${issue.status!=='resolved'&&canOperate()?`<button id="detailResolve" class="panel-action">Marcar como resolvido</button>`:''}</div>`);let validate=document.getElementById('detailValidate'),resolve=document.getElementById('detailResolve');if(validate)validate.onclick=async()=>{await api(`/api/issues/${issue.id}/validate`,{method:'POST'});closeModal();await loadIssues(false);hint('Erro validado.')} ;if(resolve)resolve.onclick=async()=>{await api(`/api/issues/${issue.id}/resolve`,{method:'POST'});closeModal();await loadIssues(false);hint('Erro marcado como resolvido.')}}
function linkMidpoint(cs){if(!cs||!cs.length)return null;if(cs.length===1)return L.latLng(cs[0][1],cs[0][0]);let segments=[],total=0;for(let i=1;i<cs.length;i++){let a=L.latLng(cs[i-1][1],cs[i-1][0]),b=L.latLng(cs[i][1],cs[i][0]),length=map.distance(a,b);segments.push({a,b,length});total+=length}let wanted=total/2,walked=0;for(let s of segments){if(walked+s.length>=wanted){let t=s.length?(wanted-walked)/s.length:0;return L.latLng(s.a.lat+(s.b.lat-s.a.lat)*t,s.a.lng+(s.b.lng-s.a.lng)*t)}walked+=s.length}let last=cs[cs.length-1];return L.latLng(last[1],last[0])}
function refreshIssueVisibility(){let z=map.getZoom(),popView=z<=15;issueMarkers.forEach(b=>{let hide=false;if(b.issue.target_kind==='device')hide=popView;else if(b.issue.target_kind==='node'){let target=markers.get(`cto:${b.issue.target_id}`)||markers.get(`cloud:${b.issue.target_id}`)||markers.get(`host:${b.issue.target_id}`);hide=target&&((target.net.kind==='cto'&&z<16)||(target.net.kind==='cloud'&&z<14))}if(hide){if(map.hasLayer(b))map.removeLayer(b)}else if(!map.hasLayer(b))b.addTo(map)})}
function refreshIssueMarkers(issues){issueMarkers.forEach(m=>map.removeLayer(m));issueMarkers=[];let selected=new Map();issues.filter(i=>i.status!=='resolved').forEach(i=>{let k=`${i.target_kind}:${i.target_id}`,old=selected.get(k);if(!old||issueRank(i.severity)>issueRank(old.severity)||i.status==='pending'&&old.status!=='pending')selected.set(k,i)});selected.forEach(i=>{let point=null;if(i.target_kind==='link'){let l=links.find(x=>Number(x.id)===Number(i.target_id));if(l)point=linkMidpoint(l.display_coordinates||l.geometry.coordinates)}else{let m=markers.get(`${i.target_kind==='node'?'cto':'device'}:${i.target_id}`)||markers.get(`host:${i.target_id}`);if(m)point=m.getLatLng()}if(point){let b=L.marker(point,{icon:badgeFor(i),interactive:true,zIndexOffset:2000});b.issue=i;b.on('click',e=>{if(e.originalEvent)L.DomEvent.stopPropagation(e.originalEvent);showIssueDetails(i)});b.addTo(map);issueMarkers.push(b)}});refreshIssueVisibility()}
async function loadIssues(notify=true){let issues=await api('/api/issues'),open=issues.filter(i=>i.status!=='resolved'),pending=open.filter(i=>i.status==='pending');document.getElementById('issueCount').textContent=open.length;document.getElementById('issuesButton').title=`${open.length} erro${open.length===1?'':'s'} aberto${open.length===1?'':'s'}`;refreshIssueMarkers(issues);if(notify&&['admin','superadmin'].includes(netUser.role)){let fresh=pending.filter(i=>!seenPending.has(i.id));if(fresh.length)showIssueInbox(pending)}pending.forEach(i=>seenPending.add(i.id));return issues}
async function showIssueInbox(items=null){items=items||await api('/api/issues');let open=items.filter(i=>i.status!=='resolved');modal('Erros da rede',`<div class="issue-list">${open.map(i=>`<div class="issue-card"><b class="${i.severity==='medium'?'unkdot':i.severity==='severe'?'': 'downdot'}">${esc(i.target_name)} · ${esc(i.severity)}</b><p>${esc(i.description)}</p><small>${esc(i.reported_by_name)} · ${esc(i.status)}</small>${i.status==='pending'&&canOperate()?`<button class="validateIssue" data-id="${i.id}">Validar</button>`:''}${i.status!=='resolved'&&canOperate()?`<button class="resolveIssue" data-id="${i.id}">Resolver</button>`:''}</div>`).join('')||'<p>Nenhum erro aberto.</p>'}</div>`);document.querySelectorAll('.validateIssue').forEach(b=>b.onclick=async()=>{await api(`/api/issues/${b.dataset.id}/validate`,{method:'POST'});await showIssueInbox(await loadIssues(false))});document.querySelectorAll('.resolveIssue').forEach(b=>b.onclick=async()=>{await api(`/api/issues/${b.dataset.id}/resolve`,{method:'POST'});await showIssueInbox(await loadIssues(false))})}
document.getElementById('issuesButton').onclick=()=>showIssueInbox();
function licenseMessage(l){if(!l.configured)return'<p>Nenhuma chave foi ativada neste NetAtlas.</p>';if(l.valid)return`<p class="updot"><b>Licença válida</b></p><p>Chave: ${esc(l.license_key)}<br>Verificada: ${l.last_checked_at?new Date(l.last_checked_at).toLocaleString('pt-BR'):'agora'}${l.details?.expires_at?`<br>Expira em: ${esc(new Date(l.details.expires_at).toLocaleDateString('pt-BR'))}`:''}${l.details?.days_remaining!=null?` · ${esc(l.details.days_remaining)} dias restantes`:''}</p>`;return`<p class="downdot"><b>Licença não validada</b></p><p>${esc(l.details?.reason||'Verifique a chave e a conexão com o servidor de licenças.')}</p>`}
async function showLicense(){let l=await api('/api/license');modal('Licença · LVL - NetAtlas',`${licenseMessage(l)}<form id="licenseForm"><label>Chave de licença</label><input id="licenseKey" required autocomplete="off" placeholder="Cole a chave aqui"><p id="licenseError" class="form-error"></p><button class="primary" type="submit">Ativar e validar</button>${l.configured?'<button id="licenseRecheck" type="button">Validar novamente</button>':''}</form>`);document.getElementById('licenseForm').onsubmit=async e=>{e.preventDefault();let error=document.getElementById('licenseError');error.textContent='Validando…';try{await api('/api/license/activate',{method:'POST',body:JSON.stringify({license_key:document.getElementById('licenseKey').value})});closeModal();hint('Licença ativada e validada com sucesso.')}catch(x){error.textContent=x.message}};let check=document.getElementById('licenseRecheck');if(check)check.onclick=async()=>{try{await api('/api/license/check',{method:'POST'});closeModal();hint('Licença validada com sucesso.')}catch(x){document.getElementById('licenseError').textContent=x.message}}}
document.getElementById('licenseButton').onclick=()=>showLicense().catch(e=>hint(e.message));
async function showAuditLog(){let events=await api('/api/audit?limit=300');modal('Log de ações',`<div class="issue-list">${events.map(x=>`<div class="issue-card"><b>${esc(x.action)}</b><br><small>${esc(x.actor_username)} · ${esc(x.actor_role)} · ${new Date(x.created_at).toLocaleString('pt-BR')}</small><p>${esc(x.target_kind)}${x.target_name?` · ${esc(x.target_name)}`:x.target_id?` #${esc(x.target_id)}`:''}</p>${x.details&&Object.keys(x.details).length?`<small>${esc(Object.entries(x.details).map(([k,v])=>`${k}: ${typeof v==='object'?JSON.stringify(v):v}`).join(' · '))}</small>`:''}</div>`).join('')||'<p>Nenhuma alteração registrada ainda.</p>'}</div>`)}
document.getElementById('auditButton').onclick=()=>showAuditLog().catch(e=>hint(e.message));
document.getElementById('usersButton').onclick=()=>{modal('Criar usuário',`<form id="userForm"><label>Usuário</label><input id="newUsername" required minlength="3"><label>Nome</label><input id="newDisplayName" required><label>Perfil</label><select id="newRole"><option value="admin">Admin</option><option value="technician">Técnico</option><option value="superadmin">Superadmin</option></select><label>Senha inicial</label><input id="newPassword" type="password" required minlength="8"><p id="userError" class="form-error"></p><button class="primary" type="submit">Criar usuário</button></form>`);document.getElementById('userForm').onsubmit=async e=>{e.preventDefault();try{await api('/api/users',{method:'POST',body:JSON.stringify({username:document.getElementById('newUsername').value,display_name:document.getElementById('newDisplayName').value,role:document.getElementById('newRole').value,password:document.getElementById('newPassword').value})});closeModal();hint('Usuário criado com sucesso.')}catch(x){document.getElementById('userError').textContent=x.message}}};

function safeToRefresh(){return!mode&&!document.querySelector('.leaflet-editing-icon')}
async function refreshOperationalStatus(){if(!safeToRefresh())return;let hostIds=[...new Set([...markers.values()].map(m=>m.net.zabbix_hostid).filter(Boolean).map(Number))];if(hostIds.length){let states=await api(`/api/host-statuses?ids=${hostIds.join(',')}`),byId=new Map(states.map(s=>[Number(s.hostid),s]));for(let m of markers.values()){let hid=Number(m.net.zabbix_hostid),s=byId.get(hid);if(!s)continue;m.net.availability=s.availability;m.net.zabbix_status=s.status;m.net.ips=s.ips;m.net.down=Number(s.availability)===2;m.setIcon(mkIcon(m.net))}}await loadLinks();refreshMarkers()}
async function refreshActiveMetrics(){if(!safeToRefresh()||!activeMetricsPanel||!document.getElementById('panel').classList.contains('show'))return;let selected=activeMetricsPanel;if(selected.kind==='host'){let m=markers.get(selected.markerKey);if(m)await openHostPanel(m);return}let l=links.find(x=>Number(x.id)===selected.id),layer=null;editable.eachLayer(x=>{if(Number(x.linkId)===selected.id)layer=x});if(l&&layer)await openLinkPanel(l,layer)}
async function refreshOtherInformation(){if(!safeToRefresh())return;await loadIssues(true)}
async function startNetAtlas(){let r=await fetch('/api/auth/me');if(!r.ok){showLogin();return}netUser=await r.json();applyRole();await Promise.all([loadTopology(),loadLinks()]);await loadIssues(true);setInterval(()=>refreshOperationalStatus().catch(e=>hint(e.message)),30000);setInterval(()=>refreshActiveMetrics().catch(e=>hint(e.message)),120000);setInterval(()=>refreshOtherInformation().catch(e=>hint(e.message)),180000)}
